### ISSUE TITLE
"Show all" option on Glossary no longer working

### ISSUE THREAD

**Issue by cathanach** [leamh/leamh-wp-theme#101]

**Comment by joelsalisbury** [comment]
Hmm...not sure I understand this! I don't see a "Show all" option. Can you link to the affected page?

**Comment by cathanach** [comment]
Hi Joel,

Under every term in the Glossary is “Show All” option. I include a screenshot of it working. Let me know if questions, and thanks!

B

**[cid:image001.png@01D33069.0C8A5CD0]

**Comment by whamrick** [comment]
Not sure if the screenshot came through, but for instance, click on the Glossary entry for "a".  There are three different definitions from 3 different sources.  The Show All button used to open up all 3 definitions to display simultaneously.

**Comment by joelsalisbury** [comment]
@timthewebguy can you take a look at this?
