### ISSUE TITLE
Array for "dictionary":[ Not Working

### ISSUE THREAD

**Issue by whamrick** [leamh/leamh-wp-theme#103]
@joelsalisbury @timthewebguy 

Can't seem to get the "dictionary" attribute to work with an array.  Instead of giving each string in order, it displays all three at once.  The array for "notes" displays properly, however.

The problem word is "Cú" in _Cú Chulainn an Chroidhe Mhir_:

{
"id":"Cú",
"dictionary":[
	"cú, noun (m. & f.) Hound, here part of a proper name.",
	"cú, noun (m/f). Hound; here Cú Chulainn.",
	"cú, noun (m/f). Hound; here Cú Chulainn."
],
"form":"same (nominative singular)",
"notes":[
	"subject of the verb in the second line of the quatrain; in Irish, the subject normally follows the verb, but word-order in poetry is more flexible",
	"the subject of the verb; this is a short form of Cú Chulainn's name",
	"the subject of the verb; this is a short form of Cú Chulainn's name"
],
"glossary":"cu"
},

**Comment by whamrick** [comment]
![screen shot 2017-09-23 at 11 43 12 am](https://user-images.githubusercontent.com/23640566/30774676-899573e4-a054-11e7-9bd1-6345a06acd2f.png)

**Comment by joelsalisbury** [comment]
Hmm...

@timthewebguy I'm not particularly familiar with this portion of the code. Let me know what you think.

**Comment by tkofh** [comment]
All set, should work now!

**Comment by whamrick** [comment]
@joelsalisbury @timthewebguy 
Beautiful!  Thanks, gentlemen.
