### ISSUE TITLE
Array for "glossary": [ Functional?

### ISSUE THREAD

**Issue by whamrick** [leamh/leamh-wp-theme#104]
@joelsalisbury @timthewebguy 

For one our duplicate words in _Cú Chulainn..._, I'm trying to use an array for the "glossary" attribute, but it doesn't seem to be working.  Can we have an array for glossary?

The word at issue is "d'" (d + single quote). I checked that apostrophes were single quote, so that doesn't seem to be the issue here.

**Comment by whamrick** [comment]
![screen shot 2017-09-27 at 9 20 41 am](https://user-images.githubusercontent.com/23640566/30915842-f677fcb6-a365-11e7-8ddd-d7f70c846b7c.png)

**Comment by whamrick** [comment]
There's a possible workaround here if I create a new glossary entry for _d'_ that simply says something like "See de [slug: de] or do [slug: do-2]" and links to those two glossary entries.

This wouldn't be entirely satisfactory, but I think it's an option if the array issue can't be easily resolved.

**Comment by tkofh** [comment]
Wes, the glossary can now be an array. Let me know if this is expected behavior.

**Comment by whamrick** [comment]
@timthewebguy 

Thanks, Tim!  This works as expected now.

Closing this one.
