### ISSUE TITLE
Chunk Popovers Not Working (All Texts)

### ISSUE THREAD

**Issue by whamrick** [leamh/leamh-wp-theme#106]
@joelsalisbury @timthewebguy 

Tim, many thanks for fixing the Array issue for glossary slugs. Working beautifully now.

Possibly not related, but none of the Popovers for chunks are working anymore in any of the texts. Individual words, except for _'na_ in _Marbhadh_ still work properly, however.

**Comment by joelsalisbury** [comment]
Should be fixed! Sorry about that.
