### ISSUE TITLE
Chunks not Working: _Mór mhilleas...DG 63_, Line Break?

### ISSUE THREAD

**Issue by whamrick** [leamh/leamh-wp-theme#110]
@timthewebguy @joelsalisbury 

Two chunks, one in Quatrain 7 and one in Quatrain 8, aren't working.  These both span a line break (i.e., they begin at the end of one line and continue into the beginning of the next line).

In addition to the popover not working, the formatting on the front end is distorted.

http://leamh.org/?post_type=texts&p=3420&preview=true

With both of these, it appears that the line break could be part of the issue.  All of the words in the chunk are sequential, however -- only there's a line break/return in between.

**Comment by whamrick** [comment]
I broke each of these two chunks into two separate chunks -- one for each side of the line break.

The chunks at the beginning of Q 7 work now, but one of the chunks at the beginning of Q 8 does not:  "Ní hé mh’anam iarrfas sionn"

For this one^, I've triple-checked the JSON and cleared and re-done the highlighting, but something is still wrong.

**Comment by whamrick** [comment]
Once again, re-typed and re-entered this from scratch.  Now it works.

Closing this one...

**Comment by foundhistory** [comment]
WEIRD.


Was the original text copied from MS Word?


Wordpress sometimes imports invisible dingbats when you copy and paste text from .docx


One strategy to prevent this is to first copy the text into a plain text editor, save as .txt, and then copy again into WordPress.

________________________________

**Comment by whamrick** [comment]
I think it may have been.  We had been on the lookout for fancy apostrophes, quotes, dashes and the like. 

Great point about the invisible dingbats -- I wonder if that wasn't the problem.  

Yes, going forward, we should always copy into a plain text editor before posting.
