### ISSUE TITLE
Texts single page: when switching from one hoverbox to another or out of a hoverbox, entire page refreshes

### ISSUE THREAD

**Issue by foundhistory** [leamh/leamh-wp-theme#41]

**Comment by foundhistory** [comment]
for example, it leaves translation tab and returns to narrative tab

**Comment by joelsalisbury** [comment]
Wow! Thought I had it solved when we spoke yesterday, but actually, this took a near-rewrite of the popover logic. I think it is FINALLY working! http://leamh.org/texts/an-inaugural-ode/

**Comment by joelsalisbury** [comment]
Spoke too soon.

**Comment by joelsalisbury** [comment]
Working now.
