### ISSUE TITLE
Books and People Landing Pages

### ISSUE THREAD

**Issue by whamrick** [leamh/leamh-wp-theme#79]
[People and Books landing pages.docx](https://github.com/leamh/leamh-wp-theme/files/1041693/People.and.Books.landing.pages.docx)

**Comment by whamrick** [comment]
People and Books landing pages 

DRAFT  28 November 2016



People landing page:

Individual Person name [>linked to Individual Person landing page]
(obviously, there will be dozens of Individual People listed here)

Individual Person names should be listed alphabetically by last name.

(We could list Book Titles and Example Text titles under each person, but it might look cleaner to just have Individual Person names linked to the Individual Person landing page, where all Book and Example Text titles would be listed.)




Books landing page:

Book Title [>linked to Individual Book landing page]
Book Author [>linked to Individual Person page]
Book Editor [>linked to Individual Person landing page]
Book Translator[>linked to Individual Person landing page]
Book Publisher [>linked to Publisher website where applicable, i.e. partners]
Publication Date [plain text]

Options for how to order list of Book Titles:
1. alphabetically by Book Title
2. list sortable by Book Title, Book Author, Book Editor, Book Translator, Book Publisher, Publication Date (or some subest of these)

(option 1 is the clean option, but option 2 may be desirable)




Individual Book landing page:

Book Title [plain text]
Book Author [>linked to Individual Person page]
Book Editor [>linked to Individual Person landing page]
Book Translator[>linked to Individual Person landing page]
Book Publisher [>linked to Publisher website where applicable, i.e. partners]
Publication Date [plain text]


Individual Person landing page:

Book Title [>linked to Individual Book landing page]
(may have several Book Titles per person)

Example Text Title [>linked to Individual Example Text landing page]
(Keating, e.g. may have more than one Example Text)

**Comment by joelsalisbury** [comment]
In progress. ETA 8/16 EOD

**Comment by whamrick** [comment]
Get rid of Source for Grammar -- only show Source for Glossary

**Comment by whamrick** [comment]
Add new field to Person entry on wordpress backend for ainm.ie link.  (Ainm.ie is an online biographical dictionary for people associated with the Irish language.)

**Comment by joelsalisbury** [comment]
Are these all set?

**Comment by whamrick** [comment]
On main Books landing page (the list of titles), Brendan was hoping to only show fields where we have data. 

For instance, if no Author is selected (as for an edited collection by various poets), then we should have no Author field show up for that book title.  Right now, it says "Author: Anonymous" even though Anonymous wasn't selected under Authors.  Can the default be to not display where no Author or Translator or Editor is selected?

Also, I know Brendan wanted the publisher/publication date to show for each title.  Can we simply display the "Citation" field here along with Author/Editor/Translator (where applicable)?

**Comment by whamrick** [comment]
On the individual Person landing page, e.g. Geoffrey Keating, we had hoped to display the sample Texts associated with that person in addition to the glossary source texts associated with that person.

For Keating, this would be "Marbhadh Chloinne hUisnigh" (and we'll be adding another one by Keating sometime in the very near future.

Just copying and pasting from our issues list from last week (feel free to chat/email for clarification on any of this):

People:

•	individual Person landing page should also display any example Texts associated with the person. (This should be a separate category from the books used for the construction of the glossary, but this can be explained at next meeting)

•	For glossary source texts associated with a Person, instead of “Geoffrey Keating is the author of:” should read:

“Geoffrey Keating is the author of the following books used in the construction of the site:”

•	For example Texts associated with a Person, should read:

“Geoffrey Keating is the author of the following Texts ["Texts" linked to main Texts landing page]:”

**Comment by whamrick** [comment]
On individual Book landing page, instead of “Source For These Words:”, change to read:

“Source for the following words found in the Glossary ["Glossary" linked to main Glossary landing page]:”

**Comment by joelsalisbury** [comment]
@timthewebguy this and the "show all" link should be considered the priority at the moment. Thanks!

**Comment by tkofh** [comment]
Show all now toggles everything!

**Comment by whamrick** [comment]
Huzzah!
