### ISSUE TITLE
JSON: Identical id Strings Need Unique Popover Content

### ISSUE THREAD

**Issue by whamrick** [leamh/leamh-wp-theme#84]
In the JSON file, how do we differentiate between identical words within the same Sample Text?

For instance, in _Brian Ó Ruairc_ we have two separate instances of "id":"budh", each with its own, unique popover content.  The second instance (in the last line) appears to be populating with the popover content associated with the first instance of "budh."

**Comment by whamrick** [comment]
Same issue relates to "lór" (i.e. both populated by popover content associated with first instance of "lór").

However, with "na," which appears three (3) times in the poem, all three are populated with the second instance of "na" (perhaps this was the first one entered?).

**Comment by joelsalisbury** [comment]
@timthewebguy we will have to look closely at this...

**Comment by joelsalisbury** [comment]
We will have a way around this. It's on its way. Not as catastrophic or "heavy lift" as we thought initially.

**Comment by joelsalisbury** [comment]
We discovered a way around this and will send a sample updated JSON file to illustrate the required changes. Also by 8/16

**Comment by tkofh** [comment]
<img width="1288" alt="screen shot 2017-08-16 at 9 46 26 am" src="https://user-images.githubusercontent.com/18562577/29366362-d3b92df4-8267-11e7-90d5-e681ebf9cdc7.png">

And there we have it. Multiple notes for any given word. You'll also notice that you can now make things bold (done by wrapping the text in *'s), italic (wrapping the text in _'s) and underline (wrapping the text in ~'s)

Please review, and I will close the issue.

**Comment by tkofh** [comment]
The system now supports arrays for all of the values. N.B. I renamed 'Form Here' to 'Form' as this makes more sense grammatically in cases of multiple forms. Closing for now, feel free to re open if there are additional issues.
