### ISSUE TITLE
"sources" on prepositions page deleted

### ISSUE THREAD

**Issue by whamrick** [leamh/leamh-wp-theme#87]
This is on the right-hand side within individual preposition entries: "Sources / All".  

This is an artifact from an earlier conception of the Grammar and is no longer needed.

**Comment by tkofh** [comment]
If I'm reading this correctly, the "sources / all" should be removed from just preposition pages. If this is not the case, let me know and I will reopen this issue. 

http://leamh.org/grammar/de/
