### ISSUE TITLE
Glossary: hide letters that have no entries

### ISSUE THREAD

**Issue by whamrick** [leamh/leamh-wp-theme#88]
Historically, Irish doesn't have letters "J" or "K" for example, and we currently have no entries for those letters.  However, it's possible that loan-words from English (or Greek, etc.) that begin with non-Irish letters could end up being in the glossary.

Can we therefore simply hide letters with no glossary entries, rather than delete letters altogether?

**Comment by joelsalisbury** [comment]
Oh my. This has opened up a fun can of worms. Got it hiding all empty letters, but in doing so we get a few hiccups with special characters. Not a huge issue as most are generally located near identifiable characters.
