### ISSUE TITLE
Can main navigation bar remain at top when navigating Glossary?

### ISSUE THREAD

**Issue by whamrick** [leamh/leamh-wp-theme#90]
Would it be possible for the main navigation bar ("Texts Grammar Glossary Books People [Search]") to remain at the top of the page when navigating the Glossary? ( I.e., when you click on a particular letter and get scrolled down to the first entry for that letter.)

**Comment by tkofh** [comment]
It looks like the bar is at the top, closing this for now. If this is not what is desired, let me know and I will re-open.
