### ISSUE TITLE
Refine search function

### ISSUE THREAD

**Issue by whamrick** [leamh/leamh-wp-theme#93]
Search now returns results with links (great!), but it seems that glossary entries, for example, have low priority/weight.  (There may be other issues.)

For instance, when a search term is also a glossary entry, the glossary entry may be on the 5th page of results, while texts using the word will be returned first.

**Comment by joelsalisbury** [comment]
@timthewebguy, we discussed that if this cannot be improved we are just going to hide the search form for the time being. Can you let me know where we're at with this?

**Comment by tkofh** [comment]
hidden for now.
